services:
  db:
    image: postgres:16-alpine
    container_name: geofinance-db
    environment:
      POSTGRES_DB: geofinance
      POSTGRES_USER: geouser
      POSTGRES_PASSWORD: geopass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geouser -d geofinance"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - geofinance-net

  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: geofinance-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      QUARKUS_HTTP_PORT: "8282"
      DB_JDBC_URL: jdbc:postgresql://db:5432/geofinance
      DB_USERNAME: geouser
      DB_PASSWORD: geopass
      DB_SCHEMA: public
      FLYWAY_MIGRATE_AT_START: "true"
      HIBERNATE_DDL: none
      CONNECT_TIMEOUT: "5000"
      READ_TIMEOUT: "15000"
    ports:
      - "8282:8282"
    networks:
      - geofinance-net

volumes:
  db_data:

networks:
  geofinance-net:
    driver: bridge
